baseurl: /open-arrow
host: 0.0.0.0
markdown: kramdown
highlighter: rouge

oa-version: 1.1.0
glyph-name: [
  "leftwards arrow",
  "upwards arrow",
  "rightwards arrow",
  "downwards arrow",
  "left right arrow",
  "up down arrow",
  "north west arrow",
  "north east arrow",
  "south east arrow",
  "south west arrow",
  "leftwards arrow with stroke",
  "rightwards arrow with stroke",
  "leftwards wave arrow",
  "rightwards wave arrow",
  "leftwards two headed arrow",
  "upwards two headed arrow",
  "rightwards two headed arrow",
  "downwards two headed arrow",
  "leftwards arrow with tail",
  "rightwards arrow with tail",
  "leftwards arrow from bar",
  "upwards arrow from bar",
  "rightwards arrow from bar",
  "downwards arrow from bar",
  "up down arrow with base",
  "leftwards arrow with hook",
  "rightwards arrow with hook",
  "leftwards arrow with loop",
  "rightwards arrow with loop",
  "left right wave arrow",
  "left right arrow with stroke",
  "downwards zigzag arrow",
  "upwards arrow with tip leftwards",
  "upwards arrow with tip rightwards",
  "downwards arrow with tip leftwards",
  "downwards arrow with tip rightwards",
  "rightwards arrow with corner downwards",
  "downwards arrow with corner leftwards",
  "anticlockwise top semicircle arrow",
  "clockwise top semicircle arrow",
  "north west arrow to long bar",
  "leftwards arrow to bar over rightwards arrow to bar",
  "anticlockwise open circle arrow",
  "clockwise open circle arrow",
  "leftwards harpoon with barb upwards",
  "leftwards harpoon with barb downwards",
  "upwards harpoon with barb rightwards",
  "upwards harpoon with barb leftwards",
  "rightwards harpoon with barb upwards",
  "rightwards harpoon with barb downwards",
  "downwards harpoon with barb rightwards",
  "downwards harpoon with barb leftwards",
  "rightwards arrow over leftwards arrow",
  "upwards arrow leftwards of downwards arrow",
  "leftwards arrow over rightwards arrow",
  "leftwards paired arrows",
  "upwards paired arrows",
  "rightwards paired arrows 1",
  "downwards paired arrows",
  "leftwards harpoon over rightwards harpoon",
  "rightwards harpoon over leftwards harpoon",
  "leftwards double arrow with stroke",
  "left right double arrow with stroke",
  "rightwards double arrow with stroke",
  "leftwards double arrow",
  "upwards double arrow",
  "rightwards double arrow",
  "downwards double arrow",
  "left right double arrow",
  "up down double arrow",
  "north west double arrow",
  "north east double arrow",
  "south east double arrow",
  "south west double arrow",
  "leftwards triple arrow",
  "rightwards triple arrow",
  "leftwards squiggle arrow",
  "rightwards squiggle arrow",
  "upwards arrow with double stroke",
  "downwards arrow with double stroke",
  "leftwards dashed arrow",
  "upwards dashed arrow",
  "rightwards dashed arrow",
  "downwards dashed arrow",
  "leftwards arrow to bar",
  "rightwards arrow to bar",
  "leftwards thick arrow",
  "upwards thick arrow",
  "rightwards thick arrow",
  "downwards thick arrow",
  "upwards thick arrow from bar 1",
  "upwards thick arrow from bar",
  "upwards thick arrow on pedestal with horizontal bar",
  "upwards thick arrow on pedestal with vertical bar",
  "upwards thick double arrow",
  "upwards thick double arrow on pedestal",
  "rightwards thick arrow from wall",
  "north west arrow to corner",
  "south east arrow to corner",
  "up down thick arrow",
  "right arrow with small circle",
  "downwards arrow leftwards of upwards arrow",
  "rightwards paired arrows",
  "leftwards arrow with vertical stroke",
  "rightwards arrow with vertical stroke",
  "left right arrow with vertical stroke",
  "leftwards arrow with double vertical stroke",
  "rightwards arrow with double vertical stroke",
  "left right arrow with double vertical stroke",
  "leftwards open headed arrow",
  "rightwards open headed arrow",
  "left right open headed arrow"
]